# yaml-language-server: $schema=./config-schema.yaml

config:
  HOSTNAME: 127.0.0.1
  LOGGING_LEVEL: DEBUG
  RECEIVE_SIZE: 1000
  SOCKET_TIMEOUT: 1

nodes:
  N1:
    MAC: N1
    IP: 0x12
    wire: W1

  N2:
    MAC: N2
    IP: 0x13
    wire: W1

  N3:
    MAC: N3
    IP: 0x22
    wire: W2
    firewall: true
    
  N4:
    MAC: N4
    IP: 0x32
    wire: W3

  R1:
    MAC: R1
    IP: 0x11
    wire: W1

  R2:
    MAC: R2
    IP: 0x21
    wire: W2

  R3:
    MAC: R3
    IP: 0x31
    wire: W3

wires:
  W1: 8001
  W2: 8002
  W3: 8003