# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  venv:
    status:
      - "test -d venv"
    cmds:
      - python -m venv venv
    silent: false
  install:
    sources:
      - requirements.txt
    deps:
      - venv
    cmds:
      - venv/Scripts/python -m pip install -r requirements.txt
    silent: false
  default:
    deps:
      - install
    cmds:
      - venv/Scripts/python src/main.py
