# https://taskfile.dev
# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

tasks:
  venv:
    status:
      - "test -d .venv"
    cmds:
      - uv venv --seed
  install:
    sources:
      - pyproject.toml
    status:
      - '[ -n "$(.venv/Scripts/pip freeze)" ]'
    deps:
      - venv
    cmds:
      - uv sync
  default:
    deps:
      - install
    cmds:
      - uv run src/main.py {{.CLI_ARGS}}
